url: http://thepixelary.com/
baseurl: 

# Site settings
title: The Pixelary
email: mike@thepixelary.com
description: "The Pixelary is a newly established Vancouver-based animation studio founded by Mike Pan."


# Team names, titles and social links
people:
- name: Mike Pan
  pic: 1
  position: Founder
  social:
    - title: twitter
      url: #themikepan
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/ThePixelary
  - title: facebook
    url: http://www.facebook.com/thepixelary
  - title: instagram
    url: http://www.instagram.com/thepixelary/
  - title: google-plus
    url: http://plus.google.com/

# Postal address (add as many lines as necessary)
address:
  - line: Vancouver BC Canada

# Build settings
markdown: kramdown
permalink: pretty